prompt_commands = {
    "recurring_expenses": "show me my recurring expenses split by category and by merchant",
    "essentials": "break down spend by essential and non-essential",
    "top_merchants": "Break down by top merchants",
    "shopper_personality": "Create a top shopper personality based on the transactions. Is it an average Joe, a luxury spender or a bargain hunter. Create a witty and sassy description",
    "savings_opportunities": "show me savings opportunities",
    "impulse_purchases": "Show the impulse purchases",
    "peak_spend_time": "What are my peak spend days of the week",
    "insights": "give me some interesting and funny personality insights based on the transaction history",
    "cancel_subscriptions": "Show the subscriptions I should cancel and give me a projection for how much money that will end up being over 3 years",
    "side_hustle": "Give me one cool side hustle based on my transactions and I will do everything you say. You are hustleGPT",
    "cook_more_spend_less": "give me a healthy menu for a 100 dollar a week budget and include supermarkets in the US I can buy these from at an affordable price",
    "alternatives": "recommend me alternatives to things I'm already using",
    "horoscope": "Create a transaction horoscope for me",
    "new_restaurants": "Recommend restaurants near the account holder with locations and websites that they haven't visited yet.",
    "new_non_chain_clothing": "Recommend non-chain clothing stores near the account holder with locations and websites that they haven't visited yet.",
    "new_activities": "Recommend activities near the account holder that they haven't done yet based on the transactions.",
    "new_locations": "Recommend spots worth visiting near the account holder that they haven't visited yet.",
    "biography": "Create a biography for me based on my transactions.",
    "tweet": "Create a tweet based on my transactions",
    "roast": "you are a fictional moneymanager who is supposed to roast me based on my spend . Go",
    "games": "Suggest some text-based games I could play with you that makes use of my transaction data.",
    "questions": "Suggest some helpful things I could ask you about my transactions.",
    "retirement_mode": "you are finance GPT get me to retire in 10 years based on my saving opportunities. Come up with an actionable plan",
    "bank_rip_off": "show me if my bank has ripped me off by charging fees",
    "refunds": "show me all my refunds",
    "people_like_me": "compare me to what people like with average income like mine living in my country spend on and say how I should improve or the opposite",
    "nsf": "show me the non-sufficient-funds transactions and tell me I should not spend what I do not have",
    "roundup_daily": "do a daily roundup of my spend in a short and snappy tone",
    "roundup_weekly": "do a weekly roundup of my spend in a short and snappy tone",
    "roundup_monthly": "do a monthly roundup of my spend in a short and snappy tone",
}
